### ISSUE TITLE
Support self-hosted GitLab

### ISSUE THREAD

**Issue by tech4him1** [igk1972/netlify-cms-oauth-provider-go#1]
Can this support self-hosted GitLab CE/EE? Looking at the Gothic provider, it looks like it can, but I'm not sure how to set it up with this package.

> // These vars define the Authentication, Token, and Profile URLS for Gitlab. If
> // using Gitlab CE or EE, you should change these values before calling New.
> //
> // Examples:
> //	gitlab.AuthURL = "https://gitlab.acme.com/oauth/authorize
> //	gitlab.TokenURL = "https://gitlab.acme.com/oauth/token
> //	gitlab.ProfileURL = "https://gitlab.acme.com/api/v3/user

https://github.com/markbates/goth/blob/ed4f7378f4655f3c2200f93627e7edcf223b1445/providers/gitlab/gitlab.go#L19-L25

**Comment by igk1972** [comment]
Thanks!
Added in https://github.com/igk1972/netlify-cms-oauth-provider-go/commit/656fb591778ba1a0aa3b918c956fe95ec3270e13

**Comment by tech4him1** [comment]
@igk1972 Great! I haven't tested it yet, but I think you have to call `NewCustomisedURL` instead of just `New`. Can you check that out?

**Comment by igk1972** [comment]
See https://github.com/igk1972/netlify-cms-oauth-provider-go/commit/3bfb3059818902abfb323c3f347e623e0aea09e4
Rework and test

**Comment by tech4him1** [comment]
Awesome, much better than my example!

**Comment by gijo-varghese** [comment]
Any docs on how to host a site from self-hosted GitLab GitLab to Netlify?

**Comment by tech4him1** [comment]
@gijo-varghese For site hosting on Netlify, you will need to contact them at http://netlify.com/support to get it set up. If you are talking about using the CMS with a self-hosted GitLab instance, that is already available (see https://www.netlifycms.org/docs/authentication-backends/#gitlab-backend).
